version: '3.9'

services:
  db:
    image: mysql:latest
    container_name: pizzeria-data
    environment:
      MYSQL_DATABASE: pizzeria
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: plam
      MYSQL_PASSWORD: rootpass
    ports:
      - "33061:3306"
    volumes:
      - ./data:/var/lib/mysql
  app:
    build: .
    container_name: pizzeria-app
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=plam
      - MYSQL_PASSWORD=rootpass
      - MYSQL_DB=pizzeria
      - MYSQL_CHARSET=utf8mb4
    depends_on:
      - db
